version: '3.9'
services:
  sonarqube:
    image: sonarqube:latest
    ports:
      - "9999:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-db:5432/sonarqube
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar_pass

  sonarqube-db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=sonarqube
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-container
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/lib/jenkins
      - /var/run/docker.sock:/var/run/docker.sock
    user: root

volumes:
  sonarqube_data:
  postgres_data:
  jenkins_data: